apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1ms18cs135-demo
  namespace: default
  labels:
     app: mynode-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynode-demo
  template:
    metadata:
      labels:
        app: mynode-demo
    spec:
      containers:
      - name: nodeapp
        image: venkatesh2000/vote
---
apiVersion: v1
kind: Service
metadata:
  name: mynode-demo
  namespace: default
  labels:
     app: mynode-demo
spec:
  type: NodePort
  selector:
     app: mynode-demo
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30135



